---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
    tag: latest
inputs:
- name: repo
params:
  CONTEXT: repo
run:
  path: build
outputs:
- name: image