---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: gerritk/ytt
    tag: latest
inputs:
- name: repo
outputs:
- name: repo
run:
  path: /bin/sh
  args:
  - -exc
  - |
    ytt -f repo/ci/ytt/schema.yaml -f repo/ci/ytt/common.yaml -f repo/ci/pipeline.yaml > repo/ci/ytt-pipeline.yaml