resources:
- name: repo
  type: git
  source:
    uri: git@github.com:kodah012/todolist.git
    branch: main
    tag_filter: "*"
    private_key: |
            ((khoa-git.private-key))

- name: todolist
  type: registry-image
  icon: docker
  source:
    repository: 10.109.32.50:5000/todolist
    insecure: true

jobs:
- name: sync-pipeline
  serial: true
  public: true
  plan:
  - get: repo
    trigger: true
  - set_pipeline: self
    file: repo/ci/pipeline.yaml
- name: build-and-push
  public: true
  plan:
  - get: repo
    trigger: true
  - task: get-tag
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gitea/gitea
      inputs:
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args:
        - -cx
        - |
          cd repo
          echo $(git tag --list "v*" | sort -V | tail -n1) > tag

  - task: build-and-push
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: repo
      outputs:
      - name: image
      params:
        CONTEXT: repo/frontend
      run:
        path: build
  - put: todolist
    params:
      image: image/image.tar
      additional_tags: repo/tag
