#@ load("@ytt:data", "data")

resources:
- name: repo
  type: git
  icon: github
  source:
    uri: git@github.com:kodah012/todolist.git
    branch: main
    tag_filter: "*"
    private_key: |
            ((khoa-git.private-key))

- name: todolist-frontend
  type: registry-image
  icon: docker
  source:
    repository: 10.109.32.50:5000/todolist-frontend
    insecure: true

- name: todolist-backend
  type: registry-image
  icon: docker
  source:
    repository: 10.109.32.50:5000/todolist-backend
    insecure: true

jobs:
- name: build-ytt-pipeline
  public: true
  plan:
    - get: repo
      trigger: true
    - task: build-ytt-pipeline
      file: repo/ci/tasks/build-ytt-pipeline.yaml
      output_mapping:
        repo: repo
    - set_pipeline: self
      file: repo/ci/ytt-pipeline.yaml

- name: build-and-push
  public: true
  plan:
  - get: repo
    trigger: true
    passed: [build-ytt-pipeline]

  - task: build-nginx-config
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
          tag: latest
      params:
        NGINX_PORT: 1337
      inputs:
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args:
        - -cx
        - |
          cd repo/frontend
          NGINX_PORT=$NGINX_PORT envsubst < nginx.conf > nginx.conf

  - task: get-tag
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gitea/gitea
      inputs:
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args:
        - -cx
        - |
          cd repo
          echo $(git tag --list "v*" | sort -V | tail -n1) > tag
  #@ for image in data.values.images:
  - task: #@ "build-{}".format(image.name)
    file: repo/ci/tasks/build.yaml
    privileged: true
    params:
      CONTEXT: #@ "repo/{}".format(image.name)
    output_mapping:
      image: #@ "{}_image".format(image.name)

  - put: #@ "todolist-{}".format(image.name)
    params:
      image: #@ "{}_image/image.tar".format(image.name)
      additional_tags: repo/tag
  #@ end
